# Generated by Django 5.2.2 on 2025-06-06 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneradorElectrico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('capacidad_tanque', models.FloatField()),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DatosConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('consumo', models.FloatField()),
                ('nivel_actual', models.FloatField()),
                ('generador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='combustible_api.generadorelectrico')),
            ],
        ),
    ]
