# Generated by Django 5.2.2 on 2025-06-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generadorelectrico',
            name='nivel_actual',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
