# Generated by Django 5.2.2 on 2025-06-12 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combustible_api', '0002_generadorelectrico_nivel_actual'),
    ]

    operations = [
    ]
