# Generated by Django 5.2.2 on 2025-08-08 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combustible_api', '0002_add_timestamps_and_ordering'),
        ('combustible_api', '0003_auto_20250612_1229'),
    ]

    operations = [
    ]
