# Generated by Django 5.2.2 on 2025-08-08 17:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible_api', '0005_backfill_timestamps_and_not_null'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datosconsumo',
            options={'ordering': ['-fecha'], 'verbose_name': 'Datos de Consumo', 'verbose_name_plural': 'Datos de Consumos'},
        ),
        migrations.AlterModelOptions(
            name='generadorelectrico',
            options={'ordering': ['id'], 'verbose_name': 'Generador Eléctrico', 'verbose_name_plural': 'Generadores Eléctricos'},
        ),
        migrations.AlterField(
            model_name='datosconsumo',
            name='consumo',
            field=models.FloatField(verbose_name='Consumo (L)'),
        ),
        migrations.AlterField(
            model_name='datosconsumo',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='datosconsumo',
            name='generador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='combustible_api.generadorelectrico'),
        ),
        migrations.AlterField(
            model_name='datosconsumo',
            name='nivel_actual',
            field=models.FloatField(verbose_name='Nivel Actual (L)'),
        ),
        migrations.AlterField(
            model_name='generadorelectrico',
            name='capacidad_tanque',
            field=models.FloatField(verbose_name='Capacidad del Tanque (L)'),
        ),
        migrations.AlterField(
            model_name='generadorelectrico',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'Mantenimiento')], default='activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='generadorelectrico',
            name='modelo',
            field=models.CharField(max_length=100, verbose_name='Modelo del Generador'),
        ),
        migrations.AlterField(
            model_name='generadorelectrico',
            name='nivel_actual',
            field=models.FloatField(default=0, verbose_name='Nivel Actual (L)'),
        ),
    ]
